
const api_key ="f9dccc2bb95ded95a527497fb023dd8b" ;
console.log(api_key)
export default {
  fetchTrending:{
    title:"Trending",
    url:`/trending/all/week?api_key=${api_key}&language=en-US`
  },
  fetchTopRated:{
    title:"Top Rated",
    url:`/movie/top_rated?api_key=${api_key}&language=en-US`
  },
  fetchActionMovies:{
    title:"Action",
    url:`/discover/movie?api_key=${api_key}&with_geners=28`
  },
  fetchComedyMovies:{
    title:"Comedy",
    url:`/discover/movie?api_key=${api_key}&with_geners=35`
  },
  fetchHorrorMovies:{
    title:"Horror",
    url:`/discover/movie?api_key=${api_key}&with_geners=27`
  },
  fetchAdventureMovies:{
    title:"Adventure",
    url:`/discover/movie?api_key=${api_key}&with_geners=12`
  },
  fetchHorrorMovies:{
    title:"Horror",
    url:`/discover/movie?api_key=${api_key}&with_geners=27`
  },
  fetchAnimationMovies:{
    title:"Animation",
    url:`/discover/movie?api_key=${api_key}&with_geners=16`
  },
  fetchCrimeMovies:{
    title:"Crime",
    url:`/discover/movie?api_key=${api_key}&with_geners=80`
  },
  fetchDocumentaryMovies:{
    title:"Documentary",
    url:`/discover/movie?api_key=${api_key}&with_geners=90`
  },
  fetchDramaMovies:{
    title:"Drama",
    url:`/discover/movie?api_key=${api_key}&with_geners=18`
  },
  fetchFamilyMovies:{
    title:"Family",
    url:`/discover/movie?api_key=${api_key}&with_geners=10751`
  },
  fetchFantasyMovies:{
    title:"Fantasy",
    url:`/discover/movie?api_key=${api_key}&with_geners=14`
  },
  fetchHistoryMovies:{
    title:"History",
    url:`/discover/movie?api_key=${api_key}&with_geners=36`
  },
  fetchMisteryMovies:{
    title:"Mystery",
    url:`/discover/movie?api_key=${api_key}&with_geners=9648`
  },
  fetchRomanceMovies:{
    title:"Romance",
    url:`/discover/movie?api_key=${api_key}&with_geners=10749`
  },
  fetchScienceMovies:{
    title:"Science",
    url:`/discover/movie?api_key=${api_key}&with_geners=878`
  },
  fetchTVMovies:{
    title:"TV",
    url:`/discover/movie?api_key=${api_key}&with_geners=10770`
  },
  fetchThrillerMovies:{
    title:"Thriller",
    url:`/discover/movie?api_key=${api_key}&with_geners=53`
  },
  fetchWarMovies:{
    title:"War",
    url:`/discover/movie?api_key=${api_key}&with_geners=10752`
  },
  fetchWesternMovies:{
    title:"Western",
    url:`/discover/movie?api_key=${api_key}&with_geners=37`
  },
  fetchMusicMovies:{
    title:"Music ",
    url:`/discover/movie?api_key=${api_key}&with_geners=10402`
  },
};
